services:
  nextjs-frontend:
    image: amarisg/counselling-chatbot-nextjs-frontend
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000" 
    networks:
      - app-network

  fastapi-backend:
    image: amarisg/counselling-chatbot-fastapi-backend
    build:
      context: .
      dockerfile: Dockerfile.backend 
    env_file:
      - .env
    ports:
      - "8000:8000" 
    # depends_on:
    #   - selenium
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
